apiVersion: v2
name: generic-service
description: A generic service chart using helmet library
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: helmet
    version: 0.14.0
    repository: https://charts.companyinfo.dev
    import-values:
      - defaults
